# © Copyright IBM Corporation 2018, 2020
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dist: bionic
group: beta
sudo: required
language: go

go:
  - "1.13.15"

services:
  - docker

env:
  global:
    - MAIN_BRANCH=v9.2.3
    - MQ_LTS_VERSION=9.2.0.1
    - TAGCACHE_FILE=tagcache
    - RELEASE=r1
    - RELEASE_LTS=r1

go_import_path: "github.com/ibm-messaging/mq-container"

# cache:
#   directories:
#     - downloads

jobs:
  include:
    - stage: basic-build
      if: branch != v9.2.3 AND tag IS blank
      name: "Basic AMD64 build"
      os: linux
      env:
        - MQ_ARCHIVE_REPOSITORY_DEV=$MQ_923_ARCHIVE_REPOSITORY_DEV_AMD64
      script: bash -e travis-build-scripts/run.sh

    # CD Build

    - stage: global-tag
      if: branch = v9.2.3 AND type != pull_request OR tag =~ ^release-candidate*
      name: "Generate Global Tag"
      os: linux
      script: bash -e travis-build-scripts/global-tag.sh
    - stage: build
      if: branch = v9.2.3 OR tag =~ ^release-candidate*
      name: "Multi-Arch AMD64 build"
      os: linux
      env:
        - BUILD_ALL=true
        - MQ_ARCHIVE_REPOSITORY=$MQ_923_ARCHIVE_REPOSITORY_AMD64
        - MQ_ARCHIVE_REPOSITORY_DEV=$MQ_923_ARCHIVE_REPOSITORY_DEV_AMD64
      script: bash -e travis-build-scripts/run.sh
    # - if: branch = v9.2.3 OR tag =~ ^release-candidate*
    #   name: "Multi-Arch PPC64LE build"
    #   os: linux-ppc64le
    #   env:
    #     - BUILD_ALL=true
    #     - TEST_OPTS_DOCKER="-run TestGoldenPathWithMetrics"
    #     # - MQ_ARCHIVE_REPOSITORY=$MQ_923_ARCHIVE_REPOSITORY_PPC64LE
    #     - MQ_ARCHIVE_REPOSITORY_DEV=$MQ_923_ARCHIVE_REPOSITORY_DEV_PPC64LE
    #   script: bash -e travis-build-scripts/run.sh
    - stage: build
      if: branch = v9.2.3 OR tag =~ ^release-candidate*
      name: "Multi-Arch S390X build"
      os: linux-s390
      env:
        - BUILD_ALL=true
        - TEST_OPTS_DOCKER="-run TestGoldenPathWithMetrics"
        - MQ_ARCHIVE_REPOSITORY=$MQ_923_ARCHIVE_REPOSITORY_S390X
        - MQ_ARCHIVE_REPOSITORY_DEV=$MQ_923_ARCHIVE_REPOSITORY_DEV_S390X
      script: bash -e travis-build-scripts/run.sh
    - stage: push-manifest
      if: branch = v9.2.3 AND type != pull_request OR tag =~ ^release-candidate*
      name: "Push Manifest-list to registry"
      env:
        - PUSH_MANIFEST_ONLY=true
      script: bash -e travis-build-scripts/run.sh

      # LTS Build

    - stage: global-tag
      if: branch = v9.2.3 AND type != pull_request OR tag =~ ^release-candidate*
      name: "Generate Global Tag"
      os: linux
      env:
        - LTS=true
        - TAGCACHE_FILE=tagcache-lts
        - MQ_VERSION=$MQ_LTS_VERSION
        - RELEASE=$RELEASE_LTS
      script: bash -e travis-build-scripts/global-tag.sh
    - stage: build
      if: branch = v9.2.3 OR tag =~ ^release-candidate*
      name: "Multi-Arch AMD64 build"
      os: linux
      env:
        - LTS=true
        - TAGCACHE_FILE=tagcache-lts
        - MQ_VERSION=$MQ_LTS_VERSION
        - MQ_ARCHIVE_REPOSITORY=$MQ_9201_EUS_ARCHIVE_REPOSITORY_AMD64
        - RELEASE=$RELEASE_LTS
      script: bash -e travis-build-scripts/run.sh
    - stage: build
      if: branch = v9.2.3 OR tag =~ ^release-candidate*
      name: "Multi-Arch S390X build"
      os: linux-s390
      env:
        - LTS=true
        - TAGCACHE_FILE=tagcache-lts
        - MQ_VERSION=$MQ_LTS_VERSION
        - TEST_OPTS_DOCKER="-run TestGoldenPathWithMetrics"
        - MQ_ARCHIVE_REPOSITORY=$MQ_9201_EUS_ARCHIVE_REPOSITORY_S390X
        - RELEASE=$RELEASE_LTS
      script: bash -e travis-build-scripts/run.sh
    - stage: push-manifest
      if: branch = v9.2.3 AND type != pull_request OR tag =~ ^release-candidate*
      name: "Push Manifest-list to registry"
      env:
        - LTS=true
        - TAGCACHE_FILE=tagcache-lts
        - MQ_VERSION=$MQ_LTS_VERSION
        - PUSH_MANIFEST_ONLY=true
        - RELEASE=$RELEASE_LTS
      script: bash -e travis-build-scripts/run.sh

before_install:
  - make install-build-deps
  - make install-credential-helper

install:
  - echo nothing

before_script: echo nothing

after_success:
  - make lint
